### ISSUE TITLE
QuatLookAtV implementation

### ISSUE THREAD

**Issue by pwaller** [go-gl/mathgl#31]
The [QuatLookAtV](https://github.com/go-gl/mathgl/blob/master/mgl64/quat.go#L381) function has two implementations, one commented out.

For me, the two implementations do something quite different, and it lead to a lot of building hacks to try and get it to work before realising that the non-matrix implementation just works out of the box as expected.

@Jragonmiris do you have any intuition as to why, or should I try and untangle my example?

From my perspective I would prefer to standardize on the Quat implementation, but I guess first I need to understand why it was written as the matrix implementation.

I also note that to get it to work for my case I had to insert a negative sign on the angle parameter to `QuatRotate()`, but that might just be that I haven't spent enough time untangling my coordinate system.

**Comment by shurcooL** [comment]
This issue is now closed. The README should be updated to reflect that, see:

https://github.com/go-gl/mathgl#currently-deprecated-functions
