### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by horryq** [go-gl/mathgl#44]
I want to use [Sourcegraph](https://sourcegraph.com) for mathgl code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/go-gl/mathgl. (It should only take 30 seconds.)

Thank you!

**Comment by slimsag** [comment]
https://sourcegraph.com/github.com/go-gl/mathgl

Done & Cheers :)
