### ISSUE TITLE
Usage with OpenGL

### ISSUE THREAD

**Issue by dv343** [go-gl/mathgl#45]
This is probably a stupid question, but I ask because I didn't find the answer on the documentation.
How can I pass a mgl32 vector/matrix to OpenGL?

**Comment by shurcooL** [comment]
Take a look at one of the examples.

https://github.com/go-gl/examples/blob/1552b3384ccfe67f4cfd6b5440be0485775f25e6/glfw31-gl41core-cube/cube.go#L64-L74

You can also use the `gl.Ptr` helper to get address of the matrices.

**Comment by dv343** [comment]
Thanks, that's exactly what I was looking for, it will be nice if there was an easy to find link to it.

**Comment by shurcooL** [comment]
The last paragraph of the first section in README says:

> Examples can be found in github.com/go-gl/examples.

But I don't think it's very visible.

**Comment by dv343** [comment]
You're right, but that link is not marked as as link (<a> and </a> tags are missing)
