### ISSUE TITLE
Matrix multiplication MulNx1 is incorrect

### ISSUE THREAD

**Issue by shogg** [go-gl/mathgl#48]
A matrix `mat Mat3x6` with 3 rows and 6 columns multiplicated with a vector `v Vec6` should yield a `Vec3`. But `MulNx1` currently expects `mat` to have 6 rows and tries to produce a `Vec6`: panic: index out of range.

correction in matmn.go line 416:
```go
//	dst = dst.Resize(len(v.vec))
	dst = dst.Resize(mat.m)

//	for r := range v.vec {
	for r := 0; r < mat.m; r++ {
```

Also:
func VecN.Set is missing. There is MatMxN.At, MatMxN.Set, VecN.Get but no VecN.Set.

**Comment by Jragonmiris** [comment]
Can you submit a PR?

Also, it's plausible we should get rid of MatM/VecN. If people want to do arbitrary-dimensional matrix math, they should probably use GoNum. The big hurdle here is that we're CMO and it's RMO, and it's potentially expensive to do a bunch of transposes just to feed data to another library.

**Comment by hydroflame** [comment]
My bad, not there isnt for VecN
